### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by LittleFlorence** [troy351/Zhengfang-Evaluation#1]
控制台那里显示评价已完成但实际上没评完。之前手动评价了一门多课，只有那两门上面有评价信息，第三门开始没有。会不会是要求评价的条 数不同导致的呢。
是的，用这个脚本每门课的评价只评价了11条，而我们要评价22条。脚本中没有明确的数字显示我也不知道怎么改。是指针的问题？（

**Comment by troy351** [comment]
循环我只写了11条，因为我们学校的评价只有11条，由于没有途径测试别的学校的情况，所以导致了这个问题。本身正方系统对每个学校都有单独定制过，所以有些内容可能不同学校不一样，没有办法面面俱到。

**Comment by troy351** [comment]
本人刚刚毕业没有办法再测试了，故无法更改，如果能看懂代码的话欢迎帮忙改进^_^

**Comment by LittleFlorence** [comment]
噗 之前都没有点进.js文件里看过，点进去之后就知道把12改成23了……
